/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorPersona;
import ec.edu.ups.controlador.ControladorTelefono;
import ec.edu.ups.dao.PersonaDAO;
import ec.edu.ups.dao.TelefonoDAO;
import ec.edu.ups.modelo.Persona;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class VentanaActualizarPersona extends javax.swing.JInternalFrame {

    /**
     * Creates new form ActualizarPersona
     */
    Persona p;
    PersonaDAO personaDAO = new PersonaDAO();
    TelefonoDAO telefonoDAO = new TelefonoDAO();
    ControladorPersona controladorPersona = new ControladorPersona();
    ControladorTelefono controladorTelefono = new ControladorTelefono();
    String nuevaCedula = "";
    String nuevoNombre = "";
    String nuevoApellido = "";
    
   

    public VentanaActualizarPersona(ControladorPersona controladorPersona) {
        initComponents();
        p = new Persona();
        this.controladorPersona = controladorPersona;
        mostrar();
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        actualizarPersonabtn = new javax.swing.JButton();
        nuevaCedulatxt = new javax.swing.JTextField();
        nuevoNombretxt = new javax.swing.JTextField();
        nuevoApellidotxt = new javax.swing.JTextField();
        ingresarbtn = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 0)));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("ACTUALIZACIÓN");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Ingrese la cédula del usuario a actualizar");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Nuevo Nombre:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Nuevo Apellido:");

        actualizarPersonabtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        actualizarPersonabtn.setText("ACTUALIZAR USUARIO");
        actualizarPersonabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarPersonabtnActionPerformed(evt);
            }
        });

        nuevaCedulatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaCedulatxtActionPerformed(evt);
            }
        });

        nuevoNombretxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoNombretxtActionPerformed(evt);
            }
        });

        nuevoApellidotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoApellidotxtActionPerformed(evt);
            }
        });

        ingresarbtn.setText("Ingresar");
        ingresarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(actualizarPersonabtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(89, 89, 89)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nuevoApellidotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nuevoNombretxt, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nuevaCedulatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88)
                                .addComponent(ingresarbtn)))))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevaCedulatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingresarbtn))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nuevoNombretxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nuevoApellidotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(actualizarPersonabtn)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void nuevaCedulatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaCedulatxtActionPerformed
        // TODO add your handling code here:
        mostrar();
        nuevaCedulatxt.setText(nuevaCedula);

    }//GEN-LAST:event_nuevaCedulatxtActionPerformed

    private void nuevoNombretxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoNombretxtActionPerformed
        // TODO add your handling code here:

            nuevoNombretxt.setEditable(false);
            if(nuevaCedulatxt.getText().equals(p.getCedula())){
            nuevoNombretxt.setEditable(true);
            nuevoNombretxt.setText(nuevoNombre);
        }
        
    }//GEN-LAST:event_nuevoNombretxtActionPerformed

    private void nuevoApellidotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoApellidotxtActionPerformed
        // TODO add your handling code here:
         
        if(nuevaCedulatxt.getText().equals(p.getCedula())){
            nuevoApellidotxt.setEditable(true);
            nuevoApellidotxt.setText(nuevoApellido);
        }else{
            JOptionPane.showMessageDialog(null, "Usuario no encontrado", "Error", 0);
        }
    }//GEN-LAST:event_nuevoApellidotxtActionPerformed

    private void actualizarPersonabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarPersonabtnActionPerformed
        // TODO add your handling code here:
        if (nuevaCedulatxt.getText().equals("") || nuevoNombretxt.getText().equals("") || nuevoApellidotxt.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Rellene todas las casillas", "Error", 0);
        } else {
            String nuevaCedula = nuevaCedulatxt.getText();
            String nuevoNombre = nuevoNombretxt.getText();
            String nuevoApellido = nuevoApellidotxt.getText();

            p = new Persona(nuevaCedula, nuevoNombre, nuevoApellido);
            personaDAO.update(p);
        }
        if (nuevaCedulatxt.getText().equals(nuevaCedula) || nuevoNombretxt.getText().equals(nuevoNombre) || nuevoApellidotxt.getText().equals(nuevoApellido)) {

            JOptionPane.showMessageDialog(null, "Usuario actualizado con éxito");
        }

        reiniciar();

    }//GEN-LAST:event_actualizarPersonabtnActionPerformed

    private void ingresarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarbtnActionPerformed
        // TODO add your handling code here:
                if(nuevaCedulatxt.getText().equals(nuevaCedula)){
                    nuevoNombretxt.setEnabled(true);
                    nuevoApellidotxt.setEnabled(true);
                    JOptionPane.showMessageDialog(null, "Usuario existente");
                    
                }else{
                    JOptionPane.showMessageDialog(null, "El usuario no existe", "Error", 0);
                    nuevoNombretxt.setEnabled(false);
                    nuevoApellidotxt.setEnabled(false);
                }
                
                
    }//GEN-LAST:event_ingresarbtnActionPerformed

    public void reiniciar() {

        nuevaCedulatxt.setText("");
        nuevoNombretxt.setText("");
        nuevoApellidotxt.setText("");

    }
    
    public void mostrar(){
        
         nuevoNombretxt.setEnabled(false);
         nuevoApellidotxt.setEnabled(false);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarPersonabtn;
    private javax.swing.JButton ingresarbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nuevaCedulatxt;
    private javax.swing.JTextField nuevoApellidotxt;
    private javax.swing.JTextField nuevoNombretxt;
    // End of variables declaration//GEN-END:variables
}
